### PR TITLE
pip install ci-watson instead of conda install

### PR DESCRIPTION
**Pull request by jdavies-st**
We will be stopping maintaining the conda package of `ci-watson`.  So we want everyone to just `pip install` it.

Other changes in this PR:
 - `pip` is provided by default in conda python
 - `requests` was only needed because the conda package of `ci-watson` doesn't actually include it
- ~`stsci.imagestats` should probably be installed from pypi instead of from github.~

### CODE REVIEW

**Comment by mfixstsci** [comment]
Looks like you need to rebase?

**Comment by jdavies-st** [comment]
No, there's something wrong with the way `stsci.imagestats` is being installed/built by `pip`.  I see why you had it pulled from Github, but it tells me there is actually something wrong in the package (or its interaction with the conda packages here) which we should fix.  But maybe not for this PR.

**Comment by mfixstsci** [comment]
Ah, I see from the details now. I will look into that later this afternoon.

**Comment by jdavies-st** [comment]
No, no need to look into it.  I think it is outside the scope of `jwst_validation_notebooks`.  It looks like the version available of `stsci.imagestats` on astrconda is some dev version (which should not be the case), and for some reason the pypi version doesn't install correctly.  I'll file issues elsewhere.

**Comment by mfixstsci** [comment]
Ah! By `but it tells me there is actually something wrong in the package` you didn't mean this package. I'm tracking now, thanks for the information.

**Comment by jdavies-st** [comment]
No, no need to look into it.  I think it is outside the scope of `jwst_validation_notebooks`.  It looks like the version available of `stsci.imagestats` on astrconda is some dev version (which should not be the case), and for some reason the pypi version doesn't install correctly.  I'll file issues elsewhere.

**Comment by mfixstsci** [comment]
Hey @jdavies-st sorry for the long reply on this. I am seeing that your last commit is still failing because of something to do with `stsci.imagestats`. Pey Liam suggested github solution to install image stats for this same reason. For some reason, by default, when you pip install this package it installs `stsci.imagestats 0.0.0.dev143+gc35fb578 ` even when trying to pin a version of the software.

**Comment by jdavies-st** [comment]
Thanks @mfixstsci.  I've added it to the requirements.txt file now.

**Pull request merged**
