### PR TITLE
flat_field testing notebook

### PR DESCRIPTION
**Pull request by penaguerrero**

### CODE REVIEW

**Comment by cracraft** [comment]
The flat_field notebook crashed with the following errors.

Running flat field test for FS...
Filename: fs_prism_nrs1_interpolatedflat.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     280   ()      
  1  SCI           1 ImageHDU        14   (435, 40)   float32   
  2  DQ            1 ImageHDU        11   (435, 40)   int32 (rescales to uint32)   
  3  ERR           1 ImageHDU         9   (435, 40)   float32   
  4  WAVELENGTH    1 ImageHDU         9   (435, 40)   float32   
  5  SCI           2 ImageHDU        14   (436, 40)   float32   
  6  DQ            2 ImageHDU        11   (436, 40)   int32 (rescales to uint32)   
  7  ERR           2 ImageHDU         9   (436, 40)   float32   
  8  WAVELENGTH    2 ImageHDU         9   (436, 40)   float32   
  9  SCI           3 ImageHDU        14   (435, 45)   float32   
 10  DQ            3 ImageHDU        11   (435, 45)   int32 (rescales to uint32)   
 11  ERR           3 ImageHDU         9   (435, 45)   float32   
 12  WAVELENGTH    3 ImageHDU         9   (435, 45)   float32   
 13  SCI           4 ImageHDU        14   (432, 23)   float32   
 14  DQ            4 ImageHDU        11   (432, 23)   int32 (rescales to uint32)   
 15  ERR           4 ImageHDU         9   (432, 23)   float32   
 16  WAVELENGTH    4 ImageHDU         9   (432, 23)   float32   
 17  ASDF          1 BinTableHDU     11   1R x 1C   [258748B]   
flat_field_file  -->     Grating:PRISM   Filter:CLEAR   LAMP:LINE4
Using D-flat: /private/var/folders/qq/59kq_9pn42d5fg_5wxzzwx1w0004_p/T/tmpzp8js707/nirspec_dflat_nrs1_f_01.03.fits
Using S-flat: /private/var/folders/qq/59kq_9pn42d5fg_5wxzzwx1w0004_p/T/tmpzp8js707/nirspec_FS_sflat_PRISM_OPAQUE_FLAT5_nrs1_f_01.01.fits

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-ee88de2b035c> in <module>
     67             if 'fs' in uncal_file.lower():
     68                 print('Running flat field test for FS...')
---> 69                 result, result_msg, log_msgs = nptt.calwebb_spec2_pytests.auxiliary_code.flattest_fs.flattest(
     70                                                                                 flat_field_object,
     71                                                                                 dflat_path=dflat,

~/anaconda3/envs/jwst_validation_notebooks_test/lib/python3.8/site-packages/nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_fs.py in flattest(step_input_filename, dflat_path, sflat_path, fflat_path, writefile, show_figs, save_figs, interpolated_flat, threshold_diff, output_directory, debug)
    195         sfim = sfile_hdu["SCI"].data
    196         sfimdq = sfile_hdu["DQ"].data
--> 197         sfv = sfile_hdu["VECTOR"].data
    198 
    199     # need to flip/rotate image into science orientation

~/anaconda3/envs/jwst_validation_notebooks_test/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py in __getitem__(self, key)
    310         try:
    311             return self._try_while_unread_hdus(super().__getitem__,
--> 312                                                self._positive_index_of(key))
    313         except IndexError as e:
    314             # Raise a more helpful IndexError if the file was not fully read.

~/anaconda3/envs/jwst_validation_notebooks_test/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py in _positive_index_of(self, key)
    765         """
    766 
--> 767         index = self.index_of(key)
    768 
    769         if index >= 0:

~/anaconda3/envs/jwst_validation_notebooks_test/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py in index_of(self, key)
    746 
    747         if (found is None):
--> 748             raise KeyError(f'Extension {key!r} not found.')
    749         else:
    750             return found

KeyError: "Extension 'VECTOR' not found."

**Comment by penaguerrero** [comment]
This is odd. I am currently testing this notebook and so far is succeeding.

**Comment by cracraft** [comment]
Do we have the same environments? I have NPTT 1.1.12

**Comment by penaguerrero** [comment]
yes, same environment. I just did a git pull from master on this branch to make sure. Can you re-load NPTT? (i.e. in your terminal type git+https://github.com/spacetelescope/nirspec_pipe_testing_tool@1.1.12)

**Comment by cracraft** [comment]
Updated notebook passed convert.py test. Merging.

**Pull request merged**
