### PR TITLE
Add Box download function to template notebook

### PR DESCRIPTION
**Pull request by york-stsci**
Add a Box download function along with a sample list to the template notebook.

### CODE REVIEW

**Comment by cracraft** [comment]
My one comment here is that this section should probably replace the 'Reading in data' section on reading in data from box. There is a markup section below your addition that talks about reading in data from Artifactory and Box, and we now have two sets of instructions on how to use Box, which will be confusing. This addition should probably be moved down to the location of that discussion, and replace the current text on Box.

**Comment by york-stsci** [comment]
I've now updated the notebook to move everything to the 'Reading in Data from Box' section (as per comment).

**Comment by cracraft** [comment]
I think that looks really good. I'll leave this open for a few days so Alicia can review and comment, but it gets my approval for merging.

**Comment by aliciacanipe** [comment]
@york-stsci this looks great! Sorry for my delayed review.

**Review by aliciacanipe — APPROVED** [review]

**Pull request merged**
