### PR TITLE
Nirspec awcs

### PR DESCRIPTION
**Pull request by cracraft**
This pull request should only have the nirspec assign_wcs notebook, which has not yet been tested under the jwst_validation_notebooks environment. I'm not sure why it's saying it can't automatically merge it.

### CODE REVIEW

**Comment by york-stsci** [comment]
Looking under the PR "Files Changed" tab, it appears to change eight files. 

- Changes nirspec_pipe_testing_tool version in environment.yml, which is probably the issue because that line of the file has already been changed in the master version
- Adds the jwst_assign_wcs_nirspec_test.ipynb notebook
- Adds a notebook named jwst_barshadow_nirspec_test.ipynb
- Adds a notebook jwst_extract_2d_nirspec_test.ipynb
- Adds a notebook jwst_flat_field_nirspec_test.ipynb
- Adds a notebook named jwst_msa_flagging_nirspec_test.ipynb
- Adds a notebook named jwst_pathloss_nirspec_test.ipynb
- Adds a file named jwst_nirspec_msaoper_0001.json

**Comment by cracraft** [comment]
Yes, but I was only trying to add the assign_wcs notebook to the branch that I created the pull request from. Somehow, it pulled along all of Maria's notebooks and changes.

**Comment by york-stsci** [comment]
The easiest solution for this individual notebook is for me to add the notebook as a PR since I already have it as a single change in my repository.

**Comment by york-stsci** [comment]
Then you can update your fork from upstream, and have a new copy that's ready to add other single items.

**Pull request closed without merging**
