### PR TITLE
committing MIRI LRS notebooks

### PR DESCRIPTION
**Pull request by skendrew**
in this pull request we're submitting the following testing notebooks to the main repo:
- caldetector1 for LRS slitless (TSO)
- caldetector1 for imaging TSO
- assign_wcs for LRS slit
- assign_wcs for LRS slitless (TSO)
- background_subtraction for LRS slit
- flat field for LRS slit

Notebooks are organised in folders named for the pipeline steps; they have been rolled back i.e. are in unexecuted state. some link to data in Box, others were produced with locally stored data so data will have to be migrated to artifactory and code updated to that effect.

cc @ktmurray @nespinoza @cracraft

### CODE REVIEW

**Comment by cracraft** [comment]
Comment for person merging the notebooks. The conflicting files for jwst_resample_miri_testing.ipynb and validation_test_template.ipynb should be left as they already are in the repo. Nothing from this pull request should go into those notebooks.

**Comment by skendrew** [comment]
I would also hold off on merging for now as I will be making more updates for the notebooks in this PR to pull data from artifactory in all of them. Just in case someone was planning to do this imminently.

**Comment by skendrew** [comment]
months later, this pull request now also has:
* all data in all notebooks pulled from artifactory
* notebooks for slit and slitless for photom and extract1d steps
* all notebooks should be compatible with B7.6 as well as B7.5

**Comment by cracraft** [comment]
I think we can close out this pull request once @skendrew confirms that we have all of the proper notebooks already merged into the repo.

**Comment by cracraft** [comment]
Closing per Sarah's comment that all of the notebooks have been ingested into the repo.

**Pull request closed without merging**
