### PR TITLE
Changed cube visualization from click to scroller

### PR DESCRIPTION
**Pull request by aggle**
It's easier to compare slices of a cube this way. You can slide a scroller to
quickly select a slice, or have it play through automatically while looping.

### CODE REVIEW

**Comment by aggle** [comment]
Hi @cracraft, I don't have write access to the repository so I can't request a review through the Github interface, but would you please review my pull request? I made some cosmetic changes to the calwebb_coron3 notebook to make it easier to inspect the output datacubes.

**Comment by cracraft** [comment]
Hi  @aggle  I ran into an import error when I started testing the notebook. Can you test this notebook under the jwst_validation_notebooks environment as described on the main page readme and see if you can get this to run? There may be a package that we don't have included. We could then discuss including it or find another way to do this.

Do the errors below make sense to you?

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/qq/59kq_9pn42d5fg_5wxzzwx1w0004_p/T/ipykernel_24611/2182431.py in <module>
      4 from ci_watson.artifactory_helpers import get_bigdata
      5 import matplotlib.pyplot as plt
----> 6 get_ipython().run_line_magic('matplotlib', 'widget')
      7 from astropy.utils.data import download_file
      8 get_ipython().run_line_magic('config', 'InlineBackend.close_figures=False # To prevent automatic figure display when execution of the cell ends')

~/miniconda3/envs/jwst_validation_notebooks/lib/python3.9/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2349                 kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2350             with self.builtin_trap:
-> 2351                 result = fn(*args, **kwargs)
   2352             return result
   2353 

~/miniconda3/envs/jwst_validation_notebooks/lib/python3.9/site-packages/decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

~/miniconda3/envs/jwst_validation_notebooks/lib/python3.9/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/miniconda3/envs/jwst_validation_notebooks/lib/python3.9/site-packages/IPython/core/magics/pylab.py in matplotlib(self, line)
     97             print("Available matplotlib backends: %s" % backends_list)
     98         else:
---> 99             gui, backend = self.shell.enable_matplotlib(args.gui.lower() if isinstance(args.gui, str) else args.gui)
    100             self._show_matplotlib_backend(args.gui, backend)
    101 

~/miniconda3/envs/jwst_validation_notebooks/lib/python3.9/site-packages/IPython/core/interactiveshell.py in enable_matplotlib(self, gui)
   3531                 gui, backend = pt.find_gui_and_backend(self.pylab_gui_select)
   3532 
-> 3533         pt.activate_matplotlib(backend)
   3534         configure_inline_support(self, backend)
   3535 

~/miniconda3/envs/jwst_validation_notebooks/lib/python3.9/site-packages/IPython/core/pylabtools.py in activate_matplotlib(backend)
    325     from matplotlib import pyplot as plt
    326 
--> 327     plt.switch_backend(backend)
    328 
    329     plt.show._needmain = False

~/miniconda3/envs/jwst_validation_notebooks/lib/python3.9/site-packages/matplotlib/pyplot.py in switch_backend(newbackend)
    275     backend_name = cbook._backend_module_name(newbackend)
    276 
--> 277     class backend_mod(matplotlib.backend_bases._Backend):
    278         locals().update(vars(importlib.import_module(backend_name)))
    279 

~/miniconda3/envs/jwst_validation_notebooks/lib/python3.9/site-packages/matplotlib/pyplot.py in backend_mod()
    276 
    277     class backend_mod(matplotlib.backend_bases._Backend):
--> 278         locals().update(vars(importlib.import_module(backend_name)))
    279 
    280     required_framework = _get_required_interactive_framework(backend_mod)

~/miniconda3/envs/jwst_validation_notebooks/lib/python3.9/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

~/miniconda3/envs/jwst_validation_notebooks/lib/python3.9/importlib/_bootstrap.py in _gcd_import(name, package, level)

~/miniconda3/envs/jwst_validation_notebooks/lib/python3.9/importlib/_bootstrap.py in _find_and_load(name, import_)

~/miniconda3/envs/jwst_validation_notebooks/lib/python3.9/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

~/miniconda3/envs/jwst_validation_notebooks/lib/python3.9/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~/miniconda3/envs/jwst_validation_notebooks/lib/python3.9/importlib/_bootstrap.py in _gcd_import(name, package, level)

~/miniconda3/envs/jwst_validation_notebooks/lib/python3.9/importlib/_bootstrap.py in _find_and_load(name, import_)

~/miniconda3/envs/jwst_validation_notebooks/lib/python3.9/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'ipympl'

**Comment by cracraft** [comment]
Something else to keep in mind is that on the output page, there is only a static html page displayed, and there is no interactivity allowed. If we want to see all of the images, it's better to just display all of the images somehow and not click or scroll through them. Maybe if the change to just display all of the images is made, the error seen will also go away.

**Comment by aggle** [comment]
Thanks for the review. You're right, @cracraft, I forgot when I submitted the PR that I'd installed ipympl to get the widget to work. I'll take the suggestion (@cracraft and @york-stsci) that the images should all be plotted individually rather than animated.

**Pull request closed without merging**
