### PR TITLE
LRS notebooks now use inflight data for validation

### PR DESCRIPTION
**Pull request by ktmurray**
These changes now pull and use the inflight data for analysis, as well as correct the mistake that caused the assertion error in the slit notebook.

### CODE REVIEW

**Comment by skendrew** [comment]
thanks @ktmurray! Reviewed the notebooks and they will need some further updates before we can merge. 

Slit:
- remove references to simulated data in the text and replace with an accurate description of the test data (program ID, observation number
- remove the cell that is fully commented out (where simulated files were retrieved)
- the text still talks about the output of the flat field step, when we are using the output of the path loss step. please update the text so it reflects what the code is doing?
- update the "last updated" date. 

Slitless:
- would be good to have a paragraph at the top describing the data we are using, just PID and observation number is fine, and the basic outline of steps. this makes it easier to update in the future.  
- update the Last Updated date at the bottom. 

Thanks!

**Comment by cracraft** [comment]
Also, the notebook cells need to be cleared before they can be put into the repo. Before re-submitting to the PR, please use the Kernel > Restart & Clear Output option.

**Comment by ktmurray** [comment]
Okay this should have updated the pull request with the files addressing your comments - let me know if it worked!

**Comment by skendrew** [comment]
Looks good from my side @ktmurray! If @cracraft is happy with the format, this is good to merge.

**Comment by cracraft** [comment]
All tests have passed, merging into repo.

**Pull request merged**
