### PR TITLE
Adding unit test notebooks for calwebb_detector1

### PR DESCRIPTION
**Pull request by aliciacanipe**
Before merging this PR, there are a couple issues that we have to discuss/resolve:

1. I need to update the conftest.py in the jwst/ repo, because I wanted pytest to grab the docstrings for all the unit tests (this should be straightforward)
2. There are some pytest dependencies that might not work in a normal pipeline build (ipython pytest-xdist pytest-html): https://github.com/spacetelescope/jwst#installing-for-developers 
3. I tried using tempfiles in the notebooks, but I'm not sure how it would work in practice when we execute the notebooks 

So, let's hold off on trying to merge this PR for now.

### CODE REVIEW

**Comment by aliciacanipe** [comment]
A comment for myself to remember to add the following to conftest.py in the jwst/ repo:

`import pytest
import inspect

@pytest.mark.trylast
def pytest_configure(config):
    terminal_reporter = config.pluginmanager.getplugin('terminalreporter')
    config.pluginmanager.register(TestDescriptionPlugin(terminal_reporter), 'testdescription')

class TestDescriptionPlugin:

    def __init__(self, terminal_reporter):
        self.terminal_reporter = terminal_reporter
        self.desc = None

    def pytest_runtest_protocol(self, item):
        self.desc = inspect.getdoc(item.obj)

    @pytest.hookimpl(hookwrapper=True, tryfirst=True)
    def pytest_runtest_logstart(self, nodeid, location):
        if self.terminal_reporter.verbosity == 0:
            yield
        else:
            self.terminal_reporter.write('\n')
            yield
            if self.desc:
                    self.terminal_reporter.write(f'\n{self.desc} ')`

**Comment by aliciacanipe** [comment]
@york-stsci This was my draft PR for a set of unit test notebooks that I had on hold while the other issues were sorted. I think I should just be able to add the tmpdir cell to the notebooks and then we can merge these as well, right?

**Comment by york-stsci** [comment]
I think that they've already been added, so it might actually just make sense to close this PR. Unless there are test notebooks that are in this PR but haven't yet been added?

**Comment by aliciacanipe** [comment]
Yeah, these notebooks haven't been added yet, so I left the PR as a draft. But I need to add the tmpdir cells now that we have that in place.

**Comment by york-stsci** [comment]
So, there are a couple of other things that look as if they should be changed. If you look at the existing regression test notebooks, you'll see how I wrote the part of the script that runs the regression tests in those. As is, these notebooks will not run in the Jenkins environment, because the jwst module directory is not where they expect to find it, and also while the script creates a temporary directory, it then saves its output into a directory in the same directory as the notebook with the name "tmpdir", rather than using the temporary directory it defined. The already added regression tests also show how that works.

**Comment by aliciacanipe** [comment]
K sounds good, I'll work on them. Thank you!

**Comment by cracraft** [comment]
Since the unit tests were accidentally merged in a different PR, I'm closing this PR. Any updates to the unit tests will be opened as new PRs.

**Pull request closed without merging**
