### PR TITLE
Updating README with new Box instructions

### PR DESCRIPTION
**Pull request by aliciacanipe**
@cracraft @york-stsci 

I created a draft of our Box workflow using the information that Hsing-Ying Liu provided to us this morning. Let me know if this looks okay (or feel free to suggest changes!).

### CODE REVIEW

**Comment by cracraft** [comment]
Looks good to me.

**Comment by aliciacanipe** [comment]
@york-stsci are you okay with this update to the README? That's the only change in this PR. I can merge if needed.

**Comment by york-stsci** [comment]
It looks fine to me. Sorry for the slow reply. I’m out sick today.

On May 3, 2021, at 15:46, aliciacanipe ***@***.***> wrote:

﻿

@york-stsci<https://urldefense.com/v3/__https://github.com/york-stsci__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!htu6Is647KeeXtYEQO32KP5LNTviPnZFS12shM_PFgEmghP9WPbSPJNxmc5QDQ$> are you okay with this update to the README? That's the only change in this PR. I can merge if needed.

**Comment by aliciacanipe** [comment]
Oh no worries @york-stsci that was a super fast reply. I'm sorry to bug you while sick. Get some rest!

**Pull request merged**
